version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: "db"
    networks:
      - server-side
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    env_file:
      .env
    build:
      context:
        backend
    volumes:
      - ./backend/:/code/backend
    depends_on:
      db:
         condition: service_healthy
    links:
      - db
    ports:
      - '8000:8000'
    command: bash -c "python backend/manage.py migrate ;
                      python backend/manage.py fill_table_with_test_data ;
                      python backend/manage.py runserver 0.0.0.0:8000"
    networks:
      - server-side
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src:ro


networks:
  client-side: {}
  server-side: {}

volumes:
  db:
    driver: server-side