# Generated by Django 4.2.1 on 2023-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
