# Generated by Django 4.2.1 on 2023-05-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefields',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
