# Generated by Django 4.2.1 on 2023-05-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_api', '0002_alter_tablefields_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablefields',
            options={'ordering': ['id']},
        ),
    ]
